docs(jfrog): add bonita artifact repository installation
bonitasoft/bonita-test-toolkit-doc pull request #25
Opened 2022-07-25 07:27 UTC by akantcheff

BTT is now available on new Bonita Artifact Repository.

This PR is linked to https://github.com/bonitasoft/bonita-doc/pull/2079

2022-07-25 08:14 UTC, rbioteau commented
Depends on https://github.com/bonitasoft/bonita-doc/pull/2079/files

2022-07-26 13:44 UTC, uguy commented
Waiting for PR https://github.com/bonitasoft/bonita-doc/pull/2079 to be merged

2022-07-28 06:47 UTC, jbaudot85 commented on modules/ROOT/pages/installation.adoc
> +== Bonita Artifact Repository installation
I suggest to rephrase to "**Installation from** the Bonita Artifact Repository"

2022-07-28 06:49 UTC, jbaudot85 commented on modules/ROOT/pages/installation.adoc
>  == Local repository installation
I suggest to rephrase to "**Installation from the Customer Portal**"

2022-07-28 06:50 UTC, jbaudot85 commented on modules/ROOT/pages/installation.adoc
>  == Bonita Continuous Delivery installation
I suggest to rephrase "**Installation from** Bonita Continuous Delivery"

2022-07-28 11:42 UTC, uguy requested changes
LGTM, but need to change `.github/workflows/build-pr-preview.yml` to not target PR branches in preview.

2022-08-01 16:11 UTC, rbioteau commented
:partying_face: 
@akantcheff It was a bad module reference in the link + missing bonita version to build the preview

2022-08-01 16:15 UTC, akantcheff commented
> 🥳 @akantcheff It was a bad module reference in the link + missing bonita version to build the preview

The preview won't work until the PR https://github.com/bonitasoft/bonita-doc/pull/2079 is merged.

2022-08-01 16:24 UTC, rbioteau commented
https://github.com/bonitasoft/bonita-doc/pull/2079 is missing
https://github.com/bonitasoft/bonita-doc/tree/2022.2/modules/software-extensibility/pages

:thinking:

2022-08-01 16:26 UTC, rbioteau commented
OOps I thought it was merged for some reasons....
I fixed the links so it should be good when the pr is merged.

2022-08-01 16:27 UTC, akantcheff commented
Yes we create a new page in https://github.com/bonitasoft/bonita-doc/pull/2079 that we reference in this one so the preview is broken.

2022-08-09 10:25 UTC, merged